context_staging: &context_staging
  context: staging

context_prod: &context_prod
  context: prod

filter_only_tag: &filter_only_tag
  filters:
    branches:
      ignore: /.*/
    tags:
      only: /^release-v[\d]+.[\d]+.[\d]+/

version: 2.1
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run: echo Hello, world.

  deploy:
    machine: true
    steps:
      - checkout
      - run: echo ${GREETING}.

workflows:
  version: 2
  publish:
    jobs:
      - build:
          <<: *filter_only_tag
      - deploy:
          <<: *context_staging
          <<: *filter_only_tag
          requires:
            - build
      - deploy:
          <<: *context_prod
          <<: *filter_only_tag
          requires:
            - build
