context_staging: &context_staging
  context: staging

context_prod: &context_prod
  context: prod

filter_only_tag: &filter_only_tag
  filters:
    branches:
      ignore: /.*/
    tags:
      only: /^(release|staging|all)-v[\d]+.[\d]+.[\d]+/

filter_only_tag_prod: &filter_only_tag_prod
  filters:
    branches:
      ignore: /.*/
    tags:
      only: /^(release|all)-v[\d]+.[\d]+.[\d]+/

filter_only_tag_staging: &filter_only_tag_staging
  filters:
    branches:
      ignore: /.*/
    tags:
      only: /^(staging|all)-v[\d]+.[\d]+.[\d]+/

version: 2.1
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run: echo Hello, world.

  deploy:
    machine: true
    steps:
      - checkout
      - run: echo ${GREETING} ${CIRCLE_WORKFLOW_ID}.

workflows:
  version: 2
  publish:
    jobs:
      - build:
          <<: *filter_only_tag
      - deploy:
          name: Staging
          <<: *context_staging
          <<: *filter_only_tag_staging
          requires:
            - build
      - deploy:
          name: Production
          <<: *context_prod
          <<: *filter_only_tag_prod
          requires:
            - build
