version: 2
jobs:
  build:
    docker:
      - image: debian:stretch

    steps:
      - checkout

      - run:
          name: Greeting
          command: echo Hello, world.

      - run:
          name: Print the Current Time
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              "echo ${CIRCLE_BRANCH}"
            el
              "echo {Another}"
            fi
